apiVersion: v1
kind: Pod
metadata:
  name: my-sample-app-on-gcloud
spec:
  containers:
    - name: my-sample-app-on-gcloud
      image: gcr.io/go-sample-144321/go-trivial-sample
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          hostPort: 80
