apiVersion: v1
kind: Pod
metadata:
  name: my-sample-app-on-gcloud
spec:
  containers:
    - name: my-sample-app-on-gcloud
      image: gcr.io/telep-corporation/go-trivial-sample
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          hostPort: 80
